version: '3.8'
services:
  webapp_parcial:
    container_name: webapp_parcial
    image: parcial2:1.0
    build: .
    ports:
      - "4848:4848"
      - "8080:8080"
    volumes:
      - /home/djeovanz/containers/payara:/opt/payara/appserver/glassfish/domains/domain1/lib/
